databases:
  - name: THE BEST UDON_DB
    databaseName: the best udon_db
    user: THE BEST UDON
    region: singapore

services:
  - type: web
    name: THE BEST UDON
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: THE BEST UDON_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

